#!/usr/bin/env python
import os, sys
from os.path import abspath, join, dirname

top_dir = abspath(dirname(__file__))
os.chdir(top_dir)

support_dir = join(top_dir, 'MoinMoin', 'support')
sys.path.insert(0, support_dir)

from babel.messages.frontend import CommandLineInterface

trans_dir = join(top_dir, 'MoinMoin', 'translations')
potfile = join(trans_dir, 'MoinMoin.pot')

cmd = sys.argv[1]

if cmd == 'extract':
    args = "babel extract -F %(cfg)s -o %(out)s ." % dict(
               cfg=join(top_dir, 'babel.cfg'),
               out=potfile,
           )
elif cmd == 'update':
    lang = sys.argv[2]
    args = "babel update --locale %(lang)s -i %(pot)s -d %(trans_dir)s" % dict(
               pot=potfile,
               trans_dir=trans_dir,
               lang=lang,
           )
elif cmd == 'compile':
    args = "babel compile -d %(trans_dir)s" % dict(
               trans_dir=trans_dir,
           )

rc = CommandLineInterface().run(args.split())

