#!/bin/bash
# create a virtual environment in directory env/
virtualenv --no-site-packages env
source env/bin/activate
# "install" moin2 from repo to the env, this will also install
# required python packages from pypi.
pip install -e .
# compile the translations
python setup.py compile_catalog --statistics

# get some 3rd party stuff and unpack them into env/, where the default
# wikiconfig.py expects them. should be replaced by packaging.

URL=http://download.cksource.com/CKEditor/CKEditor/CKEditor%203.5/ckeditor_3.5.tar.gz
wget -O - $URL | tar xz -C env/ -f -

URL=http://static.moinmo.in/files/packages/TWikiDrawPlugin-moin.tar.gz
wget -O - $URL | tar xz -C env/ -f -

URL=http://static.moinmo.in/files/packages/svg-edit.tar.gz
wget -O - $URL | tar xz -C env/ -f -

URL=http://code.jquery.com/jquery-1.4.4.min.js
mkdir env/jquery
wget -O - $URL > env/jquery/jquery.min.js

URL=http://svgweb.googlecode.com/files/svgweb-2010-08-10-Owlephant-1.zip
wget -O env/svgweb.zip $URL 
unzip -d env/ env/svgweb.zip
rm env/svgweb.zip

URL='http://downloads.sourceforge.net/project/anywikidraw/anywikidraw/anywikidraw-0.14/anywikidraw-0.14.zip?use_mirror=ignum'
DIR='AnyWikiDraw 0.14'
wget -O env/awd.zip $URL
unzip -d env/ env/awd.zip
rm env/awd.zip
cd env/
ln -s "$DIR" AnyWikiDraw
cd ..

