#!/usr/bin/env python
import os, sys
from os.path import abspath, join, dirname

top_dir = abspath(join(dirname(__file__), '..', '..', '..'))
os.chdir(top_dir)

support_dir = join(top_dir, 'MoinMoin', 'support')
sys.path.insert(0, support_dir)
from babel.messages.frontend import CommandLineInterface

i18n_dir = join(top_dir, 'MoinMoin', 'i18n')

cmd = sys.argv[1]

if cmd == 'extract':
    args = "babel extract -F %(cfg)s -o %(out)s ." % dict(
               cfg=join(i18n_dir, 'tools', 'babel.cfg'),
               out=join(i18n_dir, 'MoinMoin.pot'),
           )
elif cmd == 'update':
    lang = sys.argv[2]
    args = "babel update --locale %(lang)s -i %(pot)s -o %(po)s" % dict(
               pot=join(i18n_dir, 'MoinMoin.pot'),
               po=join(i18n_dir, '%s.MoinMoin.po' % lang),
               lang=lang,
           )

rc = CommandLineInterface().run(args.split())

